services:

  # Backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-to-do-list
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    env_file:
    - .env

  # Database

  database:
    image: mariadb:latest
    container_name: mariadb-to-do-list
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  # Adminer

  adminer:
    image: adminer:latest
    container_name: adminer-to-do-list
    ports:
      - "9999:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  mariadb_data:
